// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export { }

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Captcha: typeof import('./src/components/Captcha.vue')['default']
    copy: typeof import('./src/components/config/GetSmscode copy.vue')['default']
    GetSmscode: typeof import('./src/components/GetSmscode.vue')['default']
    InfitiniteScroll: typeof import('./src/components/InfitiniteScroll.vue')['default']
    Layout: typeof import('./src/components/config/Layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
